version: 0.2

env:
  exported-variables:
    - AWS_DEFAULT_REGION
phases:
  install:
    runtime-versions:
      java: corretto8
  build:
    commands:
      - mvn install
      - mvn test
artifacts:
  files:
    - target/javawebdemo.war
    - appspec.yml
    - scripts/**/*
  discard-paths: no
